/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t *pClkCReg = (uint32_t*)0x40023830; //Pointer to RCC Register
	uint32_t *pPortCModReg = (uint32_t*)0x40020800; //Pointer to Port C Mode Register
	uint32_t *pPortCOutReg = (uint32_t*)0x40020814; //Pointer to Port C output data Register

	*pClkCReg |= 0x04; //Enabling the clock for GPIO peripherals in the AHB1 Bus

	//Configuration Mode
	*pPortCModReg &= 0xF3FFFFFF; //Clearing the port C
	*pPortCModReg |= 0x04000000; //Setting the port C as output

	*pPortCOutReg |= 0x2000; //Turning on Led


    /* Loop forever */
	for(;;);
}
