/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "ejemplo1.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	//Declaration of Variables
	uint32_t *pClkCReg = (uint32_t*)0x40023830; //Pointer to RCC Register
	uint32_t *pPortCModReg = (uint32_t*)0x40020800; //Pointer to Port C Mode Register
	uint32_t *pPortCOutReg = (uint32_t*)0x40020814; //Pointer to Port C output data Register

	//Instructions

	*pClkCReg = 0; //Clear port
	*pClkCReg |= (1 << 2); //Setting bit 2 of RCC high
	*pPortCModReg = 0; //Clear port
	*pPortCModReg |= (1 << 26); //Setting bit 26 of Port C mode high
	*pPortCOutReg = 0; //Clear port
	*pPortCOutReg |= (1 << 13); // Setting bit 13 of Port C output data high

	//1. Enable the clock for GPIO peripherals in AHB1
	//*pClkCReg |= 0x04;

	//Configure mode
	//pPortCModReg &= ;

	//*pPortCModReg |= ;

	//*pPortCOutReg |= 0x2000;
    /* Loop forever */
	for(;;);
}
