/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "RegLib.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC_Conf_t volatile *const pClkctrlReg = (RCC_Conf_t*)BASEADDRESSRCC;
	GPIOX_MODE_REG_t volatile *const pPortCModReg = (GPIOX_MODE_REG_t*)ADDRESSPORTCMODE;
	GPIOX_OUTDAT_REG_t volatile *const pPortCOutReg = (GPIOX_OUTDAT_REG_t*)ADDRESSPORTCOUTD;

	//Enable clock for GPIOC
	pClkctrlReg -> GPIOC_EN = ENABLE;
	//Set port Mode
	pPortCModReg -> Moder13 = OUTPUT;
	// Set pin 13 port output data high
	pPortCOutReg -> pin13 = HIGH;
    /* Loop forever */
	for(;;);
}
